class Autogenerated {
  Id _iId;
  List<Comments> _comments;
  List<String> _admins;
  List<String> _allowedUsers;
  List<String> _presentUsers;
  String _title;
  String _description;
  Status _status;
  Privacy _privacy;
  Time _time;
  V _vV;

  Autogenerated(
      {Id iId,
      List<Comments> comments,
      List<String> admins,
      List<String> allowedUsers,
      List<String> presentUsers,
      String title,
      String description,
      Status status,
      Privacy privacy,
      Time time,
      V vV}) {
    this._iId = iId;
    this._comments = comments;
    this._admins = admins;
    this._allowedUsers = allowedUsers;
    this._presentUsers = presentUsers;
    this._title = title;
    this._description = description;
    this._status = status;
    this._privacy = privacy;
    this._time = time;
    this._vV = vV;
  }

  Id get iId => _iId;
  set iId(Id iId) => _iId = iId;
  List<Comments> get comments => _comments;
  set comments(List<Comments> comments) => _comments = comments;
  List<String> get admins => _admins;
  set admins(List<String> admins) => _admins = admins;
  List<String> get allowedUsers => _allowedUsers;
  set allowedUsers(List<String> allowedUsers) => _allowedUsers = allowedUsers;
  List<String> get presentUsers => _presentUsers;
  set presentUsers(List<String> presentUsers) => _presentUsers = presentUsers;
  String get title => _title;
  set title(String title) => _title = title;
  String get description => _description;
  set description(String description) => _description = description;
  Status get status => _status;
  set status(Status status) => _status = status;
  Privacy get privacy => _privacy;
  set privacy(Privacy privacy) => _privacy = privacy;
  Time get time => _time;
  set time(Time time) => _time = time;
  V get vV => _vV;
  set vV(V vV) => _vV = vV;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _iId = json['_id'] != null ? new Id.fromJson(json['_id']) : null;
    if (json['comments'] != null) {
      _comments = new List<Comments>();
      json['comments'].forEach((v) {
        _comments.add(new Comments.fromJson(v));
      });
    }
    _admins = json['admins'].cast<String>();
    _allowedUsers = json['allowed_users'].cast<String>();
    _presentUsers = json['present_users'].cast<String>();
    _title = json['title'];
    _description = json['description'];
    _status =
        json['status'] != null ? new Status.fromJson(json['status']) : null;
    _privacy =
        json['privacy'] != null ? new Privacy.fromJson(json['privacy']) : null;
    _time = json['time'] != null ? new Time.fromJson(json['time']) : null;
    _vV = json['__v'] != null ? new V.fromJson(json['__v']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._iId != null) {
      data['_id'] = this._iId.toJson();
    }
    if (this._comments != null) {
      data['comments'] = this._comments.map((v) => v.toJson()).toList();
    }
    data['admins'] = this._admins;
    data['allowed_users'] = this._allowedUsers;
    data['present_users'] = this._presentUsers;
    data['title'] = this._title;
    data['description'] = this._description;
    if (this._status != null) {
      data['status'] = this._status.toJson();
    }
    if (this._privacy != null) {
      data['privacy'] = this._privacy.toJson();
    }
    if (this._time != null) {
      data['time'] = this._time.toJson();
    }
    if (this._vV != null) {
      data['__v'] = this._vV.toJson();
    }
    return data;
  }
}

class Id {
  String _oid;

  Id({String oid}) {
    this._oid = oid;
  }

  String get oid => _oid;
  set oid(String oid) => _oid = oid;

  Id.fromJson(Map<String, dynamic> json) {
    _oid = json['$oid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$oid'] = this._oid;
    return data;
  }
}

class Comments {
  Id _iId;
  String _mess;
  int _likes;

  Comments({Id iId, String mess, int likes}) {
    this._iId = iId;
    this._mess = mess;
    this._likes = likes;
  }

  Id get iId => _iId;
  set iId(Id iId) => _iId = iId;
  String get mess => _mess;
  set mess(String mess) => _mess = mess;
  int get likes => _likes;
  set likes(int likes) => _likes = likes;

  Comments.fromJson(Map<String, dynamic> json) {
    _iId = json['_id'] != null ? new Id.fromJson(json['_id']) : null;
    _mess = json['mess'];
    _likes = json['likes'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._iId != null) {
      data['_id'] = this._iId.toJson();
    }
    data['mess'] = this._mess;
    data['likes'] = this._likes;
    return data;
  }
}

class Status {
  String _numberInt;

  Status({String numberInt}) {
    this._numberInt = numberInt;
  }

  String get numberInt => _numberInt;
  set numberInt(String numberInt) => _numberInt = numberInt;

  Status.fromJson(Map<String, dynamic> json) {
    _numberInt = json['$numberInt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$numberInt'] = this._numberInt;
    return data;
  }
}

class Privacy {
  String _numberInt;

  Privacy({String numberInt}) {
    this._numberInt = numberInt;
  }

  String get numberInt => _numberInt;
  set numberInt(String numberInt) => _numberInt = numberInt;

  Privacy.fromJson(Map<String, dynamic> json) {
    _numberInt = json['$numberInt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$numberInt'] = this._numberInt;
    return data;
  }
}

class Time {
  Start _start;
  End _end;

  Time({Start start, End end}) {
    this._start = start;
    this._end = end;
  }

  Start get start => _start;
  set start(Start start) => _start = start;
  End get end => _end;
  set end(End end) => _end = end;

  Time.fromJson(Map<String, dynamic> json) {
    _start = json['start'] != null ? new Start.fromJson(json['start']) : null;
    _end = json['end'] != null ? new End.fromJson(json['end']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._start != null) {
      data['start'] = this._start.toJson();
    }
    if (this._end != null) {
      data['end'] = this._end.toJson();
    }
    return data;
  }
}

class Start {
  Date _date;

  Start({Date date}) {
    this._date = date;
  }

  Date get date => _date;
  set date(Date date) => _date = date;

  Start.fromJson(Map<String, dynamic> json) {
    _date = json['$date'] != null ? new Date.fromJson(json['$date']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._date != null) {
      data['$date'] = this._date.toJson();
    }
    return data;
  }
}

class Date {
  String _numberLong;

  Date({String numberLong}) {
    this._numberLong = numberLong;
  }

  String get numberLong => _numberLong;
  set numberLong(String numberLong) => _numberLong = numberLong;

  Date.fromJson(Map<String, dynamic> json) {
    _numberLong = json['$numberLong'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$numberLong'] = this._numberLong;
    return data;
  }
}

class End {
  Date _date;

  End({Date date}) {
    this._date = date;
  }

  Date get date => _date;
  set date(Date date) => _date = date;

  End.fromJson(Map<String, dynamic> json) {
    _date = json['$date'] != null ? new Date.fromJson(json['$date']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this._date != null) {
      data['$date'] = this._date.toJson();
    }
    return data;
  }
}

class V {
  String _numberInt;

  V({String numberInt}) {
    this._numberInt = numberInt;
  }

  String get numberInt => _numberInt;
  set numberInt(String numberInt) => _numberInt = numberInt;

  V.fromJson(Map<String, dynamic> json) {
    _numberInt = json['$numberInt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['$numberInt'] = this._numberInt;
    return data;
  }
}
